#! /usr/bin/python
#
# Wrapper script to start a UniConvertor frontend
#
# Copyright (C) 2010 Igor E. Novikov
#
# This library is covered by GNU Library General Public License.
# For more info see COPYRIGHTS file in uniconvw root directory.
#


from uniconvw import uniconvw_run
uniconvw_run()